const { test } = require('node:test')
const assert = require('node:assert/strict')
const { isHarnessEnvelope, mergeChatMessage } = require('../src/shared/chat-messages.ts')

// 取自真实会话记录：subagent 结束后 Claude Code 以 user 角色写回的条目。
const TASK_NOTIFICATION = `<task-notification>
<task-id>a438e67b8cbf1ea18</task-id>
<tool-use-id>toolu_bdrk_016ELqMZgoywDs972Zi7NUup</tool-use-id>
<output-file>/private/tmp/claude-501/-Users-liuao-work-jf-a2afans/09/tasks/a438e67b8cbf1ea18.output</output-file>
<status>completed</status>
<summary>Agent "Explore huaxin sell order mode and price logic" finished</summary>
<note>A task-notification fires each time this agent stops with no live background children of its own.</note>
<result>Findings below.

\`\`\`python
def on_tick(price, tick_time, volume):
    pass
\`\`\`
</result>
</task-notification>`

test('识别单块信封', () => {
  assert.equal(isHarnessEnvelope(TASK_NOTIFICATION), true)
  assert.equal(isHarnessEnvelope('<system-reminder>\nfoo\n</system-reminder>'), true)
})

test('识别连续多块信封（斜杠命令回显）', () => {
  const slashCommand = [
    '<command-name>/model</command-name>',
    '            <command-message>model</command-message>',
    '            <command-args>opus</command-args>'
  ].join('\n')
  assert.equal(isHarnessEnvelope(slashCommand), true)
})

test('识别 local-command-caveat（机器指令文本，不应展示给用户）', () => {
  const caveat =
    '<local-command-caveat>Caveat: The messages below were generated by the user while ' +
    'running local commands. DO NOT respond to these messages.</local-command-caveat>'
  assert.equal(isHarnessEnvelope(caveat), true)
})

test('允许前后空白', () => {
  assert.equal(isHarnessEnvelope(`\n\n  <system-reminder>x</system-reminder>  \n`), true)
})

test('真实提问不误判', () => {
  assert.equal(isHarnessEnvelope('自动卖出为啥会出现这种无效报价'), false)
  assert.equal(isHarnessEnvelope(''), false)
  assert.equal(isHarnessEnvelope('   '), false)
})

test('开头恰好是信封标签、但后面跟着真实提问时不丢弃', () => {
  const quoted = '<system-reminder>example</system-reminder>\n\n为什么这里会渲染成黑块？'
  assert.equal(isHarnessEnvelope(quoted), false)
})

test('缺少闭合标签（流式半截内容）不丢弃', () => {
  assert.equal(isHarnessEnvelope('<task-notification>\n<task-id>abc'), false)
})

test('正文中引用标签不误判', () => {
  assert.equal(isHarnessEnvelope('日志里出现了 <task-notification> 这种标签'), false)
})

test('mergeChatMessage：同 id 文本拼接，tool/system 整体替换', () => {
  const base = { id: 'a', role: 'assistant', content: 'he', createdAt: '2026-01-01T00:00:00.000Z' }
  assert.equal(mergeChatMessage([base], { ...base, content: 'llo' })[0].content, 'hello')

  const tool = { id: 't', role: 'system', kind: 'tool', content: 'new', createdAt: '2026-01-01T00:00:00.000Z' }
  assert.equal(mergeChatMessage([tool], { ...tool, content: 'replaced' })[0].content, 'replaced')

  assert.equal(mergeChatMessage([], base).length, 1)
})
